import "./globals.scss";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import LeftSide from "@/components/LeftSide/LeftSide";
import Header from "@/components/Header/Header";
import RightSide from "@/components/RightSide/RightSide";
import Providers from "@/components/Providers/Providers";

const jost = Jost({ subsets: ["latin"], display: "fallback" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Providers>
          <Header />
          <main>
            <LeftSide />
            <RightSide>{children}</RightSide>
          </main>
        </Providers>
      </body>
    </html>
  );
}
